USE TFI
CREATE TABLE RESPONSABLE (
    IDResponsable INT PRIMARY KEY,
    nombre NVARCHAR(100),
    apellido NVARCHAR(100),
    telefono NVARCHAR(20),
    correoElectronico NVARCHAR(100),
    CUIT CHAR(11),
    FOREIGN KEY (CUIT) REFERENCES ESTABLECIMIENTO(CUIT)
);
